name: HypGnosis
favicon: null
layout_spectrum: 0.9612337069120258
typography_spectrum: 0.7738418239168823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5408687379676849
  lightness: 0.4060412978287786
  saturation: 0.6535264614503831
  rhythmicContrast: 0.8599996652919799
purpose: []
