analytics: {}
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.540868
  lightness: 0.406041
  rhythmicContrast: 0.859999
  saturation: 0.738176
cta: {}
layout_spectrum: 0.951014
name: HypGnosis
opengraph: {}
purpose: []
typography_spectrum: 0.871622
